export const section_types = ['strength', 'metcon']
export const round_types = ['fortime', 'amrap', 'emom']
export const id = 'id'
export const workout_id = 'workout_id'
export const section_type = 'section_type'
export const score_number = 'score_reps'
export const score_time = 'score_time'
export const rounds = 'rounds'
export const round_duration = 'round_duration'
export const round_type = 'round_type'
export const extra_instructions = 'extra_instructions'
export const user = 'user'
export const buyin_number = 1
export const buyout_number = 28
