export const workoutPlannerSubmissionTodayDate = 'You successfully planned a workout. It looks like you scheduled it for today - would you like to do this workout now? If not, you will be able to return to it later on from the home screen.'
export const workoutPlannerSubmissionSuccess = 'You successfully planned this workout. You will now be returned to the home screen.'
export const workoutPlannerSubmissionFailure = 'Looks like there are a couple things missing from this workout.'
export const workoutPlannerSubmissionFailureEmptyMovements = 'Please select a movement type for each of the entries in this workout - they cannot be blank.'
export const workoutPlannerSubmissionFailureNoMovements = "Please make sure you entered a movement for each section. If you really don't want any movements in a section, just delete that whole section."
export const workoutPlannerSubmissionFailureNoSections = 'Please make sure you created at least one section for this workout.'
export const workoutLoggerUnfinishedMovements = 'Please make sure you recorded a score for every movement.'
export const workoutLoggerNetworkError = 'Something went wrong with the submission process. The app will try again in the background.'
export const workoutLoggerSubmissionSuccess = 'Nice work.'
